language: java
dist: trusty
sudo: required

services:
  - docker
  
before_install:
  - docker build -t sshj/test-sshd ./src/test/resources/
  - docker run -d -p 127.0.0.1:2222:22 sshj/test-sshd
  - docker ps -a
   
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

before_install:
  - pip install --user codecov

after_success:
- codecov
